//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevinWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Appointment_ID { get; set; }
        public Nullable<int> Appointment_PatientID { get; set; }
        public Nullable<int> Appointment_ProviderID { get; set; }
        public Nullable<int> Appointment_Trigger_EventId { get; set; }
        public string Appointment_Description { get; set; }
        public Nullable<System.DateTime> Appointment_StartTime { get; set; }
        public string Appointment_EndTime { get; set; }
    }
}
