//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevinWindowService.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevinTwilioEntities : DbContext
    {
        public DevinTwilioEntities()
            : base("name=DevinTwilioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppointmentProvider> AppointmentProviders { get; set; }
        public virtual DbSet<AppointmentType> AppointmentTypes { get; set; }
        public virtual DbSet<DashboardText> DashboardTexts { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MMDomain> MMDomains { get; set; }
        public virtual DbSet<MMSubDomain> MMSubDomains { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ScheduleMessage> ScheduleMessages { get; set; }
        public virtual DbSet<SmsReply> SmsReplies { get; set; }
        public virtual DbSet<StageInTX> StageInTXes { get; set; }
        public virtual DbSet<Trigger> Triggers { get; set; }
        public virtual DbSet<TriggerEvent> TriggerEvents { get; set; }
        public virtual DbSet<TriggerType> TriggerTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserEnrollment> UserEnrollments { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
    }
}
