//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevinWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Message_ID { get; set; }
        public string Message_Messages { get; set; }
        public Nullable<int> Message_TriggerTypeID { get; set; }
        public Nullable<int> Message_TriggerEventID { get; set; }
        public Nullable<int> Message_TriggerID { get; set; }
        public string Message_Time { get; set; }
        public string Message_FrequencyOfDelivery { get; set; }
        public string Message_If1 { get; set; }
        public string Message_If2 { get; set; }
        public string Message_OtherNotes { get; set; }
        public string Message_TimesSent { get; set; }
        public Nullable<int> Message_MMDomainID { get; set; }
        public Nullable<int> Message_MMSubDomainID { get; set; }
        public Nullable<int> Message_StageInTXID { get; set; }
    }
}
