//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevinWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsReply
    {
        public int Id { get; set; }
        public string Sid { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<int> ParentSid { get; set; }
        public Nullable<int> MessageId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MessageResponse { get; set; }
        public string SmsStatus { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
    }
}
