//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevinWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggerEvent
    {
        public int TriggerEvent_ID { get; set; }
        public Nullable<int> TriggerTypeId { get; set; }
        public string TriggerEvent_Day { get; set; }
        public string TriggerEvent_Event { get; set; }
    }
}
